// Bairros de Itapetininga para o "Primeiro do bairro" da LP (rótulos do mapa).
// A mesma lista valida o voto no banco: mude os dois juntos
// (supabase/migrations/20261007000027_bairro_interesse.sql).
export const BAIRROS = [
  "Centro",
  "Central Parque 4-L",
  "Chácara São José",
  "Jardim Bela Vista",
  "Jardim Brasil",
  "Jardim Flor de Lis",
  "Jardim Fogaça",
  "Jardim Itália",
  "Jardim Leonel",
  "Jardim Marabá",
  "Jardim Maria Luiza",
  "Jardim Mesquita",
  "Jardim Paulista",
  "Jardim Santa Inez",
  "Jardim Vieira de Moraes",
  "Parque Atenas do Sul",
  "Parque da Lagoa",
  "Reserva da Mata",
  "Vale San Fernando",
  "Vila Aliança",
  "Vila Alves",
  "Vila Aparecida",
  "Vila Arruda",
  "Vila Asem",
  "Vila Aurora",
  "Vila Bandeirantes",
  "Vila Barth",
  "Vila Camarão",
  "Vila Carolina",
  "Vila Cubatão",
  "Vila Deyse",
  "Vila Eldorado",
  "Vila Francisca",
  "Vila Godoi",
  "Vila Judith",
  "Vila Mazzei",
  "Vila Monteiro",
  "Vila Nova",
  "Vila Orestes",
  "Vila Piedade",
  "Vila Prestes",
  "Vila Progresso",
  "Vila Regina",
  "Vila Rica",
  "Vila Rio Branco",
  "Vila Rocha",
  "Vila Rosa",
  "Vila Santana",
  "Vila Serafim",
  "Vila Visaltino Gomes",
] as const;
